os: osx
osx_image: xcode7.2
language: objective-c
sudo: false

env:
  global:
    # $THEOS is absolutely needed for theos to even be found
    - THEOS=~/theos
    - ORIGDIR=$PWD

before_install:
  # os x: update homebrew and install dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install dpkg ldid; fi
  
  # install theos
  - git clone --depth=50 --branch=master https://github.com/theos/theos.git ~/theos
  - cd ~/theos
  - git submodule update --init --recursive
  - cd $ORIGDIR

script:
  # create a directory
  - cd curago
  # build!
  - make package
  # go back up
  - cd ../../
  # remove test, ready for the next one
  - rm -rf ~/theos
