os: osx
osx_image: xcode7.2
language: objective-c
sudo: false

env:
  global:
    # $THEOS is absolutely needed for theos to even be found
    - THEOS=~/theos

before_install:
  # update homebrew and install dependencies
  - brew update; fi
  - brew install dpkg ldid; fi
  
  # install theos
  git clone --recursive https://github.com/theos/theos.git ~/theos

script:
  # got to main project directory
  - cd curago
  # build!
<<<<<<< HEAD
  - make package
=======
  - make package
>>>>>>> 1ff8d454751bf0e3d681cd6eb2d33694a50815e3
