os: osx
osx_image: xcode7.2
language: objective-c
sudo: false

env:
  global:
    # $THEOS is absolutely needed for theos to even be found
    - THEOS=~/theos

before_install:
  # update homebrew and install dependencies
  - brew update; fi
  - brew install dpkg ldid; fi
  
  # install theos
  git clone --recursive https://github.com/theos/theos.git ~/theos

script:
  # got to main project directory
  - cd curago
  # build!
  - make package